---
- name: Wordpress config file
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: root
    group: apache
    mode: '0640'
    setype: etc_t
  notify: restart apache2
  tags: wordpress