---

- name: "apache installation"
  become: yes
  yum:
   name: "httpd"
   state: "present"

- name: "apache service activation"
  become: yes
  service:
   name: "httpd"
   state: "started"
   enabled: yes