---

- name: Update apt cache
  become: yes
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  become: yes
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php7.2-mysql
    - libapache2-mod-php7.2
    - python-mysqldb
    
